### ISSUE TITLE
Create Redmine Issue not working

### ISSUE THREAD

**Issue by cls97** [raidensan/RedMineIssueCreator#1]
Hi, when i click on Create RedMine Issue inside of Outlook it doesnt show the Create Issue Form

Best Regards
cls97

**Comment by raidensan** [comment]
Hi,

Thanks for using RedMine Issue Creator. Please make sure that you have entered valid values in Settings. I will try to further test in order to reproduce this issue.

Regards

**Comment by shawnzhou1120** [comment]
i have the same issue.i confirm we have save the valid values in Settings when i open outlook at 1st time.
it doesnt show the create issue Form.
i am using the outlook 2016(office 365).

**Comment by raidensan** [comment]
I am unable to reproduce the issue.
